name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Deploy when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21" # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build # Adjust this if your build command is different

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Token for authentication
          publish_dir: ./dist # Directory to publish
